version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly, day: monday, timezone: America/Guatemala }
    open-pull-requests-limit: 5
    labels: [infra]
    groups:
      minor-y-patch:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly, day: monday, timezone: America/Guatemala }
    labels: [infra]
